version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dvwa_user
      MYSQL_PASSWORD: dvwapassword
      MYSQL_DATABASE: dvwa
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  vulnerable-web-app:
    image: mostafa20022/vulnerable-web-app
    container_name: vulnerable-web-app
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dvwa_user
      MYSQL_PASSWORD: dvwapassword
      MYSQL_DATABASE: dvwa
    depends_on:
      - mariadb

  vulnerable-ssh:
    image: rastasheep/ubuntu-sshd
    container_name: vulnerable-ssh
    ports:
      - "2222:22"
    environment:
      ROOT_PASSWORD: rootpassword

  vulnerable-nginx:
    image: nginx:alpine
    container_name: vulnerable-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  mariadb_data:
