# version: '3.8'  # Use a suitable version
services:
  vulnerable-web-app:
    image: mostafa20022/vulnerable-web-app
    container_name: vulnerable-web-app
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dvwa_user
      MYSQL_PASSWORD: dvwapassword
      MYSQL_DATABASE: dvwa
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  vulnerable-nginx:
    image: nginx:alpine
    container_name: vulnerable-nginx
    ports:
      - "8081:80" # Access Nginx at this port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx config
      - ./public:/usr/share/nginx/html # Mount your public directory to serve files
